### ISSUE TITLE
Is it a bug related to padding?

### ISSUE THREAD

**Issue by HyunwooKim2** [Xilinx/BNN-PYNQ#101]
Hello
There seems to be a bug related to padding in foldedmv-offload.h of the host code.
I linked the source code below.

https://github.com/Xilinx/BNN-PYNQ/blob/32eed91994228d1042a16c692047dfe81e47d498/bnn/src/library/host/foldedmv-offload.h#L251

When initializing the interleaver, it is initialized to 32 * 32.
I think the pad size should be considered when padding.
The generated code below also should consider the size of padding.
(In addition to the code shown below, there is more to consider for padding in the generated code.)

https://github.com/Xilinx/BNN-PYNQ/blob/32eed91994228d1042a16c692047dfe81e47d498/bnn/src/network/cnvW1A1/hw/top.cpp#L163
https://github.com/Xilinx/BNN-PYNQ/blob/32eed91994228d1042a16c692047dfe81e47d498/bnn/src/network/cnvW1A1/hw/top.cpp#L168

Please let me know if I have overlooked something.
Thank you.

**Comment by giuliogamba** [comment]
The input images are not padded, they're 32x32 pixels, with 3 channels RGB and 8 bit per channel. The interleaver has the number of channels as first template parameter (3) and the size as the second (32x32).

**Comment by HyunwooKim2** [comment]
So you mean padding is not supported?
I am modifying the source somewhat on my local for input padding.
Thank you for your answer.
