### ISSUE TITLE
Its actually a doubt regarding the code

### ISSUE THREAD

**Issue by ambarish1999** [Xilinx/BNN-PYNQ#104]
typename TSrcI = Identity
can you explain what is the meaning of these kind of statements. It is used in many places in the repository. Can you mail me so that i can ask you some doubts.
I am actually trying to make a 3 layer LSTM  and trying to use the framework proposed here of multi layer cnn for the lstm.
but i am not able to understand how to take the input of one layer of lstm -pynq and pass it as the input to the other. some shape mismatches are coming if i directly do the same

**Comment by giuliogamba** [comment]
Identity mean the class is inherited by the parameter passed to the function. For example, [here](https://github.com/Xilinx/BNN-PYNQ/blob/master/bnn/src/network/cnvW2A2/hw/top.cpp#L173) the third template value, namely `TWeightI` is set to identity, meaning that for weight the function will use the class used to define the weight parameter (in the example [weights1](https://github.com/Xilinx/BNN-PYNQ/blob/master/bnn/src/network/cnvW2A2/hw/top.cpp#L53) - so FixedPointWeights with the template values used in the class). Hope this helps.
