### ISSUE TITLE
Python 3.6

### ISSUE THREAD

**Issue by songuke** [Xilinx/BNN-PYNQ#11]
The current code on master branch seems having some compilation issues with print function and tuple argument ([PEP 3113](http://legacy.python.org/dev/peps/pep-3113/)) in Python 3.6. 

I include my fixes here. FYI. 
[fix_python3.6.txt](https://github.com/Xilinx/BNN-PYNQ/files/1202187/fix_python3.6.txt)

**Comment by songuke** [comment]
Also, the current master branch seems only run on PYNQ v1.4.

**Comment by yunqu** [comment]
We have just tested v2.0, and it seems working.
