### ISSUE TITLE
how to get the deer.bin for testbench?

### ISSUE THREAD

**Issue by yupanpanwangrui** [Xilinx/BNN-PYNQ#110]
i want to use another image for testbench, but i don't know how to get the bin file like verification.bin and input.bin, can anyone help me?

**Comment by giuliogamba** [comment]
Hi, 

you can use the function `image_to_cifar` to generate the .bin file starting from an Image, as shown in [bnn.py](https://github.com/Xilinx/BNN-PYNQ/blob/master/bnn/bnn.py).
