### ISSUE TITLE
New datasets on Bnn

### ISSUE THREAD

**Issue by sxw228** [Xilinx/BNN-PYNQ#112]
I plan to train the network with my own datasets of human faces.  Do I need to use the LFC network or the cnv network? Can I train the network with new datasets without rebuilding hardware design?

**Comment by giuliogamba** [comment]
Hi, 

it is possible to train either CNV or LFC with your own dataset, the guide is available [here](https://github.com/Xilinx/BNN-PYNQ/tree/master/bnn/src/training#training-your-own-networks). If you follow that guide, you will not need to rebuild the hardware. 
If the images of your own dataset are black and white, I suggest using LFC. If the images are RGB, I would suggest CNV. 
Hope this helps
