### ISSUE TITLE
ModuleNotFoundError: No module named 'bnn'

### ISSUE THREAD

**Issue by minertom** [Xilinx/BNN-PYNQ#114]
Hi,,
I am using the BNN-PYNQ demo on the ultra96V2 board. I'm running a jupyter notebook on the board. The BNN-PYNQ was sucessfully loaded.
However, when attempting to "import bnn"  I get 

ModuleNotFoundError: No module named 'bnn'

Ok, what I found was that if I moved the ipynb file one directory up, then the jupyter notebook finds the bnn module. 

One more thing, and I believe that this is a clue, is that the directions for loading the function from github result in a failure to load.
 [sudo pip3 install git+https://github.com/Xilinx/BNN-PYNQ.git](url)
will hang and report a failure.

I think that this [git clone https://github.com/Xilinx/BNN-PYNQ.git](url) is what I used to download and install but my belief is that it changes the directory structure in that the commands in the .ipynb file look for pictures in a DIFFERENT DIRECTORY than the pictures were actually installed in. I had to edit the ipynb and py files in order to change this so that the pictures directory were found.

My belief is that the main problem, to begin with, is an incorrect installation.

Thank You
Tom

**Comment by giuliogamba** [comment]
Can you give more details about the failure of the `sudo pip3 install git+https://github.com/Xilinx/BNN-PYNQ.git` command? 
Another option is indeed to clone the repo and after that executing `sudo pip3 install ./` in the main folder. 
Does that solved your problem?

**Comment by minertom** [comment]
Hi giuliobamba,

I was just able to find your reply, and I thank you for it. I'm recovering from the combined hellscape of having no power here in Northern California for a couple of days, and then having a resulting disk failure. 

1) As best as I remember, the suggested method of installation, `sudo pip3 install git+https://github.com/Xilinx/BNN-PYNQ.git` failed with an error something to the effect that the receiver, meaning git, did not understand the command and there was like an error 128. I can't boot from that disk anymore so I can't just run the command at the moment.

2) I used `git clone https://github.com/Xilinx/BNN-PYNQ.git` in order to clone (but there were still problems). I did not do any kind of "installation" step after the clone.

3) In your post you said 

> clone the repo and after that executing sudo pip3 install ./ in the main folder.

How much different is your version of the command for cloning from my version? Also, could you please be more specific about the command "sudo pip3 install ./" ? I use pip3 to install packages but in this case what comes after the ./ ?

Thank you again.
Tom

**Comment by giuliogamba** [comment]
Hi, 

the command `pip3` is actually executing automatically the python package installation by executing the file `setup.py`. If you clone the complete repo locally on your PYNQ board, change directory to the main `BNN-PYNQ` and execute `sudo pip3 install ./` it will automatically look for the `setup.py` file and execute the installation in the same way as by executing `sudo pip3 install git+https://github.com/Xilinx/BNN-PYNQ.git`.
Hope this helps

**Comment by giuliogamba** [comment]
@minertom Does the last post solved your problem?
