### ISSUE TITLE
Variable "RAWHLS" Definition Problem

### ISSUE THREAD

**Issue by HonggangYu** [Xilinx/BNN-PYNQ#115]
Hi,

Regarding the BNN-PYNQ (https://github.com/Xilinx/BNN-PYNQ), I have met one intractable problem while compiling the source code on PYNQ-Z1 board running ubuntu system. 

Here is the problem related to my project and unsolved before:

When compiling the  "BlackBoxJam" function in the file "BNN-PYNQ/bnn/src/library/host/foldedmv-offload.h", I find that the variable "RAWHLS" at line 134 "#if defined(OFFLOAD) && defined(RAWHLS)" need to be predefined. Could you please tell me how to define the variable "RAWHLS" so that I can compile the "BlackBoxJam" with related libraries?

Thanks a lot for all your help!

**Comment by giuliogamba** [comment]
I don't think I understand the problem. 
Anyway, those variable are defined at compile time according to the need in the [make-sw.sh](https://github.com/Xilinx/BNN-PYNQ/blob/master/bnn/src/network/make-sw.sh) script. 
When we compile the code using software execution (thus compiling the HLS C++ code as software), we use the `-DRAWHLS` (line 108) flag to compile that part of the code.

**Comment by HonggangYu** [comment]
> I don't think I understand the problem.
> Anyway, those variable are defined at compile time according to the need in the [make-sw.sh](https://github.com/Xilinx/BNN-PYNQ/blob/master/bnn/src/network/make-sw.sh) script.
> When we compile the code using software execution (thus compiling the HLS C++ code as software), we use the `-DRAWHLS` (line 108) flag to compile that part of the code.

Hi Giulio, 

Thanks for your reply! Could you please introduce the difference between the code using software execution and the code using hardware execution? 

Thanks!
