### ISSUE TITLE
Control the GPIO pins using HLS C++ rather than Python

### ISSUE THREAD

**Issue by HonggangYu** [Xilinx/BNN-PYNQ#118]
Hi,

Recently I decided that I should start coding in HLS C++.  I do know a fair amount of HLS C++ but I do not know how to control the GPIO pins on the PYNQ-Z1 board.  Could you please explain to me (in the simplest way possible) how to control the GPIO pins using HLS C++ rather than python in the file "BNN-PYNQ/bnn/src/library/host/foldedmv-offload.cpp" ?  Some simple example code (to light up a led?) would be greatly appreciated. 
Thanks in advance to anyone who willingly can show me a way to control the GPIO pins using HLS C++ in the file "BNN-PYNQ/bnn/src/library/host/foldedmv-offload.cpp".

**Comment by giuliogamba** [comment]
Hi, 
please refer to PYNQ documentation for these problems that are not related to this repo. 
You can find the documentation about GPIOs interface in PYNQ [here](https://pynq.readthedocs.io/en/latest/pynq_libraries/psgpio.html).

**Comment by HonggangYu** [comment]
> Hi,
> please refer to PYNQ documentation for these problems that are not related to this repo.
> You can find the documentation about GPIOs interface in PYNQ [here](https://pynq.readthedocs.io/en/latest/pynq_libraries/psgpio.html).

Thank you!
