### ISSUE TITLE
changing BNN weight

### ISSUE THREAD

**Issue by mtenaw1** [Xilinx/BNN-PYNQ#126]
we spoke today and you told me to uncomment line 106, 130 and 130 on cifar10-gen-weights-W1A1.py. After i did that and try to runt the python code, i got this problem.

~/Desktop/BNN-PYNQ/bnn/src/training$ python cifar10-gen-weights-W1A1.py 
Using peCount = 16 simdCount = 3 for engine 0
Extracting conv-BN complex, OFM=64 IFM=3 k=3
Layer 0: 64 x 27
WMem = 36 TMem = 4
IPrecision = 1.7 WPrecision = 1.0 APrecision = 1.0
Traceback (most recent call last):
  File "cifar10-gen-weights-W1A1.py", line 110, in <module>
    m.createBinFiles(targetDirBin, str(convl))
  File "/home/afrl/Desktop/BNN-PYNQ/bnn/src/training/finnthesizer.py", line 695, in createBinFiles
    self.__wmem2bin(self.weightMem[pe], targetDir+"/"+prefix+"-"+str(pe)+"-weights.bin", self.WPrecision==1)
  File "/home/afrl/Desktop/BNN-PYNQ/bnn/src/training/finnthesizer.py", line 618, in __wmem2bin
    import bitstring   
ImportError: No module named bitstring

**Comment by giuliogamba** [comment]
You need to install the bitstring package. https://pypi.org/project/bitstring/
