### ISSUE TITLE
How to load our own dataset

### ISSUE THREAD

**Issue by mohitajais** [Xilinx/BNN-PYNQ#132]
I am using BNN- PYNQ github repo to classify images with our own dataset. For this, I have opened BNN-PYNQ/bnn/src/training folder and trying to modify cifar_10.py python file by replacing cifar 10 loaded dataset with our dataset. But I am not getting How should I modify it with my dataset wtihout using pylearn2.
Please suggest any idea.
Thanks

**Comment by nickfraser** [comment]
Hi,

Instructions to do this are available [here](https://github.com/Xilinx/BNN-PYNQ/tree/master/bnn/src/training#training-your-own-networks). If you are already familiar with numpy this should be very simple. If not, I suggest doing some numpy tutorials first.

This issue may also help you #87.

Cheers,
Nick
