### ISSUE TITLE
Reference to the Overlay loaded

### ISSUE THREAD

**Issue by addint96** [Xilinx/BNN-PYNQ#135]
Hi!

I would like to know how can i refer to the Overlay loaded? i created a new one but the overlay is loaded in bnn.py and i wanted to refer to the overlay. I don't know if i am explaining well, for example in the tutorials we have Ov = overlay ("bitstream") and then we can use Ov.video.hdmi_in. Is there any way to refer to it?

Thanks in advance.

**Comment by giuliogamba** [comment]
Hi, 

I'm not sure what's the question, but [here](https://pynq.readthedocs.io/en/v2.0/overlay_design_methodology/overlay_tutorial.html) you can find more details on how to download your own overlay using PYNQ.
