### ISSUE TITLE
Real Time Object Detection

### ISSUE THREAD

**Issue by addint96** [Xilinx/BNN-PYNQ#137]
Hello, i am trying to real time detection in pynq Z2, but  unfortunately i only get 5 FPS between read, detector and write the frame. I was looking for a answer and i found in another issue to Increase the CNV classification speed by increasing the per-layer parallelism . However, i would like to know if is it possible to connect the block to an AXI stream and if a IP to convert to the cifar10 formal would be a help too or not. All help is welcome.

Thanks in advance

**Comment by giuliogamba** [comment]
Hi, it's possible to perform the preprocessing, which is currently done in SW, in a Vivado IP. You can have a look at the preprocessing functions called in the example code and write an the HLS code to accelerate that tranformation in PL
