### ISSUE TITLE
hardware rebuild

### ISSUE THREAD

**Issue by maik123456789** [Xilinx/BNN-PYNQ#142]
Hi! I wanted to rebuild the HW but when I call the make-hw.sh script I get the following error and I don't know how to solve it.
![error](https://user-images.githubusercontent.com/54273123/92514914-062af380-f213-11ea-9444-0a4b7e7da5e7.png)

I've looked to other posts with the same issue and didn't suceed. I cloned the repository with the --recursive and also I sourced the vivado 2018.2

¿What else can I try?

In my first try worked, after that didn't work. Do I have to remove some files? I removed the whole repo and clone it again and still doesn't work.

**Comment by maik123456789** [comment]
And sometimes I get this.
![image](https://user-images.githubusercontent.com/54273123/92524745-e8658a80-f222-11ea-81a8-d64b1c1cf479.png)

**Comment by giuliogamba** [comment]
You have to set the `XILINX_BNN_ROOT` env variable to the exact locations. Move under `<clone_path>/BNN_PYNQ/bnn/src/`, type `pwd` and use that. It seems you set the variable to `Documentos/`, but you need the absolute path.
