### ISSUE TITLE
ModuleNotFoundError: No module named 'bnn'

### ISSUE THREAD

**Issue by moon5756** [Xilinx/BNN-PYNQ#144]
Hi, I just started using the PYNQ Z1.
I set up the PYNQ following the instruction provided in
https://pynq.readthedocs.io/en/latest/getting_started/pynq_z1_setup.html.

What I am a bit confused is that many of the users with the laptop environment, like me, are forced to connect the PYNQ directly to a computer (static IP) since the laptop is using wifi and the router is located far away from the laptop.

Because I don't have a internet access with the static IP(pip doesn't work), I downloaded the .zip file from https://github.com/Xilinx/BNN-PYNQ and manually placed it in /home/xilinx/jupyter_notebooks/.

I gave it a try with "CNV-BNN_Cifar10," and the very first line "import bnn" gave me an error, "ModuleNotFoundError: No module named 'bnn'." This issue can be resolved if I cp the "CNV-BNN_Cifar10" to /home/xilinx/jupyter_notebooks/BNN-PYNQ-master/ from /home/xilinx/jupyter_notebooks/BNN-PYNQ-master/notebooks/.

I wonder why other people are not experiencing  "ModuleNotFoundError: No module named 'bnn'" error.

**Comment by giuliogamba** [comment]
Hi, 
you need to install the package, moving the folder containing the repo is not enough. 
Please open a terminal, move to the `BNN-PYNQ` folder and type `sudo pip3 install ./`, this will install the package and move the example notebooks in a `bnn` folder withing the Jupiter notebooks folder and you will be able to execute the examples from there.

**Comment by moon5756** [comment]
Thanks!
