### ISSUE TITLE
BNN on COLAB

### ISSUE THREAD

**Issue by mustafatasci42** [Xilinx/BNN-PYNQ#148]
Hello everyone. 
I want to test BNN sw part on colab. 
But i dont install package BNN on google colab. How can install it?

**Comment by giuliogamba** [comment]
Hi, are you referring to the training part? In that case, you should not install the repository following the main [README](https://github.com/Xilinx/BNN-PYNQ/blob/master/README.md), but trying the flow explained [here](https://github.com/Xilinx/BNN-PYNQ/tree/master/bnn/src/training).
