### ISSUE TITLE
ERROR: Command errored out with exit status 128: git clone -q https://github.com/Xilinx/BNN-PYNQ.git /tmp/pip-req-build-juh8zblg Check the logs for full command output.

### ISSUE THREAD

**Issue by bahadir25** [Xilinx/BNN-PYNQ#150]
I enter to termina this line "sudo pip3 install git+https://github.com/Xilinx/BNN-PYNQ.git" I get "ERROR: Command errored out with exit status 128: git clone -q https://github.com/Xilinx/BNN-PYNQ.git /tmp/pip-req-build-juh8zblg Check the logs for full command output." 

Please help me

**Comment by bahadir25** [comment]
please immediately help

**Comment by bahadir25** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/68679144/108110137-e3471a00-70a3-11eb-8610-90ab92e06577.png)

**Comment by giuliogamba** [comment]
I suggest to check the logs for the full command output. What error is raised in that log?

**Comment by bahadir25** [comment]
> I suggest to check the logs for the full command output. What error is raised in that log?

I didn't understand what you mean. Can you write more clearly what is a log?

**Comment by giuliogamba** [comment]
I mean log file (https://en.wikipedia.org/wiki/Log_file), as stated in the error you should check the generated log file. 
p.s. are you sure the board is connected to internet?

**Comment by bahadir25** [comment]
So how can I check from where? Please help me

**Comment by bahadir25** [comment]
I performed earlier such as project in link https://www.youtube.com/watch?v=LoLCtSzj9BU&t=724s . It run

**Comment by giuliogamba** [comment]
You might want to read the PYNQ getting started https://pynq.readthedocs.io/en/v2.6.1/getting_started/pynq_z1_setup.html. 
If the board is plugged to your laptop, most likely it's not connected to the internet. You should connect it to a router in order to have the board connected to the internet.
