### ISSUE TITLE
After running sudo pip3.6 command,  bnn folder doesn't appers

### ISSUE THREAD

**Issue by LiYang66** [Xilinx/BNN-PYNQ#16]
Hi!  
    I run the sudo pip3.6 install git+https://github.com/Xilinx/BNN-PYNQ.git command on win10 using jupyter_notebooks terminal, after running, nothing appears in the directory of notebooks, no "bnn" folder appears. I use the PYNQ v2.0 image. From the picture below you can see that the command didn't run setup.py and didn't install the bnn-pynq.  Can anyone give me some guidance? Thank you!
![capture](https://user-images.githubusercontent.com/30934172/31958035-7a20f956-b8be-11e7-8a35-d4ad0e70504d.PNG)

**Comment by giuliogamba** [comment]
Hi LiYang66, 

it seems that the BNN package was already installed on your board. Thus, the pip install process failed. 
If you don't have the bnn subfolder in jupyter_notebooks, this might mean that the first installation did not completed successfully. 
I suggest to run the install command with the --upgrade flag: 
`sudo pip3.6 install git+https://github.com/Xilinx/BNN-PYNQ.git --upgrade`
