### ISSUE TITLE
Images per second

### ISSUE THREAD

**Issue by Ronin3502** [Xilinx/BNN-PYNQ#162]
Hi, I noticed that, in LFC-QNN_MNIST.ipynb, the results of case 1 and case 2 are both 'Inference took 28040.00 microseconds, 2.80 usec per image', which indicated there are 10,000,000 testing images, but the size of MNIST test dataset is 10,000. I cannot find the C/C++ code of python_hw-lfcW1A1-pynqZ1-Z2.so, so I failed to find the implementation of the inference function.
It would be so kind if you could explain this. Thanks.
![case_1_screenshot](https://user-images.githubusercontent.com/49109408/143533826-8a9682a7-55f2-4b7a-aa8e-4f1584b935fa.png)

**Comment by nickfraser** [comment]
I think you've misread the units here (**microseconds**, not milliseconds!):
 - 1 microsecond = 1 usec
 - 28,040us / 10,000 = 2.8us

You are correct, there are 10,000 test images.

**Comment by Ronin3502** [comment]
Oh, my bad.
I got it. Thanks a lot!
