### ISSUE TITLE
Why should we convert image file to bin file in the dataset

### ISSUE THREAD

**Issue by LiYang66** [Xilinx/BNN-PYNQ#20]
Hi! I just want to ask a simple question, but it confused me a couple of days. Why should we convert image file to bin file? How can I open the bin file? Which means if I don't know what is exactly the input data in the bin file, it is hard for me to understand the whole data flow in the BNN architecture. Looking forward for your reply! Thank you!

**Comment by giuliogamba** [comment]
I don't think I understand the question. 
.bin is the binary format format used in the Cifar-10 dataset, and we are using that to pass the images to the inference accelerator. In [https://github.com/Xilinx/BNN-PYNQ/blob/master/bnn/bnn.py](bnn.py) class there is a method called _image_to_cifar_ that changes the format.
