### ISSUE TITLE
Questions about hardware design rebuild

### ISSUE THREAD

**Issue by bramblewalls** [Xilinx/BNN-PYNQ#21]
Hi!
I am trying to rebuild the hardware design, but i find there are some problems.
My system is centos 7, and your recommend system is Ubuntu, i have no idea whether there is problem with system.My vivado version is Vivado 2017.4 webpack.
When i run the "make-hw.sh" file it says that can not find tiny_cnn. So i download tiny_cnn from https://github.com/Xilinx/xilinx-tiny-cnn. Then i copy the tiny_cnn folder to XILINX_BNN_ROOT/library/host.
I am not sure whether my tiny_cnn version is right and whether my tiny_cnn work well but problem disappear when i do like this however then new problem appear.
![default](https://user-images.githubusercontent.com/18498933/35429461-1e563600-02af-11e8-810c-79df35e79926.png)
I am not very fimilar with Vivado HLS, please give me some advices.
Thanks a lot!

**Comment by giuliogamba** [comment]
Hi, 

in the latest release, we are running c simulation by performing inference on a test image and checking the accuracy of the result. If csim fails, the HLS synthesis is not performed. 
I've just tried with 2017.4 and everything works on my side, so I have problems in reproducing the error. 
There are 2 warnings, can you please reply with the content of the warning?

**Comment by bramblewalls** [comment]
Thanks for you reply!
There is the content of the 2 warnings
![default](https://user-images.githubusercontent.com/18498933/35430783-bda747f8-02b4-11e8-9d8a-d8fd7fb1d94c.png)

**Comment by bramblewalls** [comment]
Thanks for your reply!
There is the content of the 2 warnings.
![default](https://user-images.githubusercontent.com/18498933/35430807-d791177a-02b4-11e8-8896-221e8b957e9c.png)

**Comment by bramblewalls** [comment]
Thanks for your reply!
There is the content of the 2 warnings.
![qq 20180126162154](https://user-images.githubusercontent.com/18498933/35430904-3baf04b0-02b5-11e8-9c03-7e1863666e5d.png)

**Comment by giuliogamba** [comment]
Please try to make a fresh clone with the new fix.

**Comment by bramblewalls** [comment]
My problem is solved, thank you very much!
