### ISSUE TITLE
Problem about hardware design rebuilt

### ISSUE THREAD

**Issue by younglee1** [Xilinx/BNN-PYNQ#23]
Hi!
I'm rebuilding the hardware design following the guide. But I've met some problem. 

<img width="635" alt="problem" src="https://user-images.githubusercontent.com/11716601/36964691-69600062-2092-11e8-89d5-8d11cf811b28.png">

As you can see, the problem occurs when running the **hardware synthesis**. It seems that the argument "-compile" doesn't work for the "csim_design" command. I tried to delete the argument, but it still fails with compilation error.
Could you please help me to solve the problem?

**Comment by giuliogamba** [comment]
Hi, 

unfortunately to run the csim with C++11 requirements you will need to upgrade to Vivado 2017.1 or newer. 
You can still re-execute the HW rebuild flow by commenting out the the csim instruction in the hls-syn.tcl file.

**Comment by younglee1** [comment]
Thanks, I'll try it.
