### ISSUE TITLE
Utilization Estimates of Synthesis

### ISSUE THREAD

**Issue by younglee1** [Xilinx/BNN-PYNQ#24]
Hi，
Sorry for bothering again...But I've met another confusing problem.
Here is the Utilization of my synthesis result, which is much higher than yours, especially the LUT utilization. I wonder how this happens.  
My environment is Vivado 2017.1, Ubuntu 16.04.
![utilization](https://user-images.githubusercontent.com/11716601/37036824-bd238d64-218b-11e8-9405-ae24d3083e1c.png)
Looking forward to your reply.

**Comment by giuliogamba** [comment]
This is the Vivado HLS Estimate usage, that sometimes can be conservative. 
Vivado will perform further optimizations and you should see a smaller hardware usage.

**Comment by younglee1** [comment]
Hi，
Since the synthesis result overuses the LUTs，I'm wondering can I accelerate part of BNN with FPGA？ Say pack convolutional layers and pooling layers as an IP, and leave FCLayers to
ARM core? Is that possible? If so, which files should I modify(top.cpp and ?)? And what should be paid attention to?

ps. I'm a total beginner to FPGA with no background knowledge. This project and your fast, kindly reply help me a lot. Thanks so much!

**Comment by giuliogamba** [comment]
Hi, 

are you replicating the neural network that is included in this repository? If yes, the whole network fits in the device. 
As stated in the previous reply, the report you attached is the one generated by Vivado HLS, that sometimes overestimates the resources. You should run the complete flow including Vivado synthesis and place and route using the command `./make-hw.sh cnv-pynq pynq a`. Vivado is performing further optimizations that will allow the design to be correctly implemented.

**Comment by younglee1** [comment]
OK，I'll retry it.
But I still want to know the answer to the question I mentioned above. What should I do if I just want to accelerate several layers of the neural network？

**Comment by giuliogamba** [comment]
You just implement in the top.cpp the layers that you want to be offloaded in the PL, and execute the other layers in the PS.

**Comment by younglee1** [comment]
Hi,
I want to run C/RTL Cosimulation in vivado HLS, but it always fails with "C++ compile error". In C simulation,  you choose clang as the compiler, but the default compile in Cosim is gcc. I have no idea how to change it. Could you please help me? How can I obtain the Cosim result?

**Comment by giuliogamba** [comment]
Please upgrade your Vivado version. With versions > 2017.3 you can select the compiler to clang also when you run the RTL cosim

**Comment by younglee1** [comment]
Thanks, I'll try it.

**Comment by younglee1** [comment]
Hi,
I tried to run RTL cosim with vivado_hls 2017.4, and set clang as the compiler, but it still failed.
![1](https://user-images.githubusercontent.com/11716601/37555670-70d74da4-29a8-11e8-87bf-b42668aa7384.png)
![2](https://user-images.githubusercontent.com/11716601/37555672-71292d72-29a8-11e8-9281-06b9e00d1b69.png)

Why would this happen?

**Comment by giuliogamba** [comment]
Hi, 

I don't know this problem, and I'm not able to reproduce it locally. I would assume there is a problem with your installation, since it's not able to find the clang-3.9 executable that should be installed with Vivado.

**Comment by xuebao1942** [comment]
I have met the same problem as you. Have you solved it? @younglee1

**Comment by giuliogamba** [comment]
Closed due to inactivity
