### ISSUE TITLE
Arbitrary precision fixed-point support

### ISSUE THREAD

**Issue by PhoenixShield** [Xilinx/BNN-PYNQ#25]
Dear Team,
This is awesome work. I’m wandering do we have arbitrary precision fixed point version of this framework or other counterparts?

**Comment by giuliogamba** [comment]
We are going to push later this week an update to the library that allows the selection, at HW generation time, to select the desired precision on each layer.

**Comment by giuliogamba** [comment]
Closing since the updates are already available on the repo.
