### ISSUE TITLE
Using BNN-PYNQ for speech recognition?

### ISSUE THREAD

**Issue by Er1cYang1120** [Xilinx/BNN-PYNQ#28]
Can I use your BNN-PYNQ for speech recognition? And do you have any example about that?

**Comment by giuliogamba** [comment]
Hi, 
this is a too generic question which is difficult to answer. In the literature, speech recognition inference is usually performed by mean of recurrent neural networks, like LSTMs. 
I would suggest to stay tuned for the next open-source released that will be available shortly [here ](https://github.com/Xilinx/LSTM-PYNQ).
