### ISSUE TITLE
Two questions about hls code

### ISSUE THREAD

**Issue by hokim72** [Xilinx/BNN-PYNQ#36]
Thank you for your great job.
I'm trying to grasp your hls code.
I have two question about your hls code.

The one is about the first convlayer for cnv-pynq.
I think "InPerImage" should be 32*32*3*8/24 in line 77 of convlayer.h because it have to process input image(32(H)*32(W)*3(C)*8(precision)).
Why do you use  32*32*3/24 for it?  

The other is about the slidingwindow.h
In the line 111 , 141, 160, you are missing the last element of cycles.
For example, you use (counter_internal_block < cycles_write_block-1)  instead of  (counter_internal_block < cycles_write_block)
Could you explain the reason?

**Comment by giuliogamba** [comment]
You are confusing the number of bits (32*32*3*8) with the number of streams, which depends on the width of the stream itself.
