### ISSUE TITLE
Theano Lasagne Inference

### ISSUE THREAD

**Issue by 910560** [Xilinx/BNN-PYNQ#40]
Hi, 
Apart using HLS to do inference, I would like to have sample on theano lasagne to perform inference and cross-check with HLS. 
Any example can be given?

Thanks

**Comment by ussamazahid96** [comment]
you can take a look at this inference [script](https://github.com/MatthieuCourbariaux/BinaryNet/tree/master/Run-time)

**Comment by 910560** [comment]
Good. Thanks
