### ISSUE TITLE
how to launch CO-Simulation in this Project

### ISSUE THREAD

**Issue by pochen125** [Xilinx/BNN-PYNQ#45]
I have problem to launch Co-simulation .

Could you teach me. will I have any other configure need to set up?

**Comment by giuliogamba** [comment]
Can you please elaborate on what problem do you have? Which version of Vivado tools are you using?

**Comment by giuliogamba** [comment]
If you want to execute co-simulation, you can add a line to the tcl script of the HLS synthesis [here](https://github.com/Xilinx/BNN-PYNQ/blob/master/bnn/src/network/hls-syn.tcl), after the `csynth_design` has been executed. The instruction should be: 
`cosim_design -argv "$directory_params $test_image 10 $expected_result" -compiler clang` 
added after line 78 and before the exit. Tested with Vivado HLS 2017.4.

**Comment by giuliogamba** [comment]
Closing, solution provided
