### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by YNZH** [Xilinx/BNN-PYNQ#47]
When I am running "sudo pip install  "...this BNN-PYNQ.git" in pynq2.3 on PYNQ-Z2 Board ,some errors are as follows:
File "bnn/bnn.py" ,line 30,in <module>
    from pynq import Overlay,PL
ImportError:No module named pynq

**Comment by giuliogamba** [comment]
On which board are you experiencing this?

**Comment by YNZH** [comment]
pynq-Z2

**Comment by YNZH** [comment]
> On which board are you experiencing this?

PYNQ-Z2

**Comment by giuliogamba** [comment]
Are you executing this on a Jupyter notebook?

**Comment by YNZH** [comment]
> On which board are you experiencing this?
terminal by putty

**Comment by YNZH** [comment]
actually, i did not find 'pip3' command in bash . and after running python --version --> python 2.7.11

**Comment by YNZH** [comment]
i guess i should update image

**Comment by giuliogamba** [comment]
> If you are using the latest PYNQ image (2.3) you can install using `sudo pip3 install git+https://github.com/Xilinx/BNN-PYNQ.git`. If you're using an older image, you should use `sudo pip3.6 install git+https://github.com/Xilinx/BNN-PYNQ.git` instead

As I said, it depends on which PYNQ Image you are using. If you don't have pip3, most likely it's an image older than 2.3, so you should use pip3.6 instead.

**Comment by YNZH** [comment]
> > If you are using the latest PYNQ image (2.3) you can install using `sudo pip3 install git+https://github.com/Xilinx/BNN-PYNQ.git`. If you're using an older image, you should use `sudo pip3.6 install git+https://github.com/Xilinx/BNN-PYNQ.git` instead
> 
> As I said, it depends on which PYNQ Image you are using. If you don't have pip3, most likely it's an image older than 2.3, so you should use pip3.6 instead.
![tim 20180927225647](https://user-images.githubusercontent.com/24869527/46154892-aa2a6700-c2a8-11e8-94c5-fbc4d50e16d1.png)
 this is the image,butno pip ,and only python 2.7.11...

**Comment by giuliogamba** [comment]
I'm currently using the exact same image, and pip3.6 is available

**Comment by YNZH** [comment]
maybe I need to reload image .

**Comment by YNZH** [comment]
maybe I need to reload image

**Comment by giuliogamba** [comment]
Yes, flash the SD card like explained here: https://youtu.be/RiFbRf6gaK4?t=46

**Comment by giuliogamba** [comment]
@YNZH have you solved this? If yes, please close the issue.
