### ISSUE TITLE
Installing BNN library and files on Pynq-Z1 using pip3: Command "python setup.py egg_info" failed with error code 1 

### ISSUE THREAD

**Issue by Urjitmodhia** [Xilinx/BNN-PYNQ#49]
Dear all I really need help on that issue: Installing BNN library and files on Pynq-Z1 using pip3:

I am having problems with the pip install command. I really need help, the sudo pip3 intall git+..... puts that error:
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-s4880beh/

I'd also downloaded and uncompressed BNN-PYNQ to a directory and run pip3 directly on the directory with the same error:

root@pynq:/home/xilinx/jupyter_notebooks/BNN-PYNQ/bnn# sudo pip3 install ./../
Processing /home/xilinx/jupyter_notebooks/BNN-PYNQ
    Complete output from command python setup.py egg_info:                                                                             running egg_info
    creating pip-egg-info/bnn_pynq.egg-info
    writing dependency_links to pip-egg-info/bnn_pynq.egg-info/dependency_links.txt
    writing pip-egg-info/bnn_pynq.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/bnn_pynq.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/bnn_pynq.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/bnn_pynq.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/bnn_pynq.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-s4880beh/setup.py", line 97, in <module>
        if os.path.isdir(os.environ["PYNQ_JUPYTER_NOTEBOOKS"]+"/bnn/"):
      File "/usr/lib/python3.4/os.py", line 633, in __getitem__
        raise KeyError(key) from None
    KeyError: 'PYNQ_JUPYTER_NOTEBOOKS'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-s4880beh/

**Comment by giuliogamba** [comment]
Please use the latest PYNQ Image (2.3) available [here ](http://www.pynq.io/board.html).
