### ISSUE TITLE
why do I execute this code at a slow speed(pynq-z2 and pynq2.3 images)? 

### ISSUE THREAD

**Issue by YNZH** [Xilinx/BNN-PYNQ#51]
this code is included in http://192.168.2.99:9090/notebooks/bnn/CNV-BNN_Cifar10.ipynb in pynq-z2(pynq2.3)。
Concretely，in my board:
![image](https://user-images.githubusercontent.com/24869527/46663408-9d830880-cbf0-11e8-969e-8eececa01548.png)

Inference took 1582.00 microseconds
Classification rate: 632.11 images per second
   [CLASS]    [RANKING]
  Airplane       256
Automobile       379
      Bird       165
       Cat       169
      Deer       163
       Dog       244
      Frog       249
     Horse       244

      Ship       267
     Truck       268

but in this Repositories ,I see that:
![image](https://user-images.githubusercontent.com/24869527/46663408-9d830880-cbf0-11e8-969e-8eececa01548.png)
Inference took 527.00 microseconds
Classification rate: 1897.53 images per second
   [CLASS]    [RANKING]
  Airplane       256
Automobile       379
      Bird       165
       Cat       169
      Deer       163
       Dog       244
      Frog       249
     Horse       244
      Ship       267
     Truck       268

as u see, the speed in my board  is three times slower.

**Comment by giuliogamba** [comment]
The notebook screenshot uploaded have been executed on the Ultra96 board, which clocks the Neural Network accelerator at 300MHz, while you're executing on PYNQ-Z2 which is clocked at 100 MHz, thus the difference in execution time.

**Comment by YNZH** [comment]
oh..thank u



发自我的小米手机在 giuliogamba <notifications@github.com>，2018年10月9日 下午6:40写道：The notebook screenshot uploaded have been executed on the Ultra96 board, which clocks the Neural Network accelerator at 300MHz, while you're executing on PYNQ-Z2 which is clocked at 100 MHz, thus the difference in execution time.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Xilinx/BNN-PYNQ","title":"Xilinx/BNN-PYNQ","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Xilinx/BNN-PYNQ"}},"updates":{"snippets":[{"icon":"PERSON","message":"@giuliogamba in #51: The notebook screenshot uploaded have been executed on the Ultra96 board, which clocks the Neural Network accelerator at 300MHz, while you're executing on PYNQ-Z2 which is clocked at 100 MHz, thus the difference in execution time."}],"action":{"name":"View Issue","url":"https://github.com/Xilinx/BNN-PYNQ/issues/51#issuecomment-428144863"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Xilinx/BNN-PYNQ/issues/51#issuecomment-428144863",
"url": "https://github.com/Xilinx/BNN-PYNQ/issues/51#issuecomment-428144863",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [Xilinx/BNN-PYNQ] why do I execute this code at a slow speed(pynq-z2 and pynq2.3 images)?  (#51)",
"sections": [
{
"text": "",
"activityTitle": "**giuliogamba**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@giuliogamba",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Xilinx/BNN-PYNQ\",\n\"issueId\": 51,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Xilinx/BNN-PYNQ\",\n\"issueId\": 51\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Xilinx/BNN-PYNQ/issues/51#issuecomment-428144863"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 390795019\n}"
}
],
"themeColor": "26292E"
}
]
