### ISSUE TITLE
Parameters on-chip

### ISSUE THREAD

**Issue by saraballeri** [Xilinx/BNN-PYNQ#59]
Hi,
the FINN paper says that the parameters are kept on-chip removing the off-chip memory
bottleneck.
In your code, what is the point in that is possible to note that?
I saw the `allocAccelBuffer` function in `xlnkdriver.hpp`, but I think it allocates memory in /dev/mem for `accelBufIn` and `accelBufOut`.
Can you clarify me how the parameters are loaded on-chip?
Thanks,

Sara

**Comment by giuliogamba** [comment]
Network parameters are stored in chip, as written in the paper, like [here](https://github.com/Xilinx/BNN-PYNQ/blob/master/bnn/src/network/cnvW1A2/hw/top.cpp) line 50 to 67. 
Input images and output classification are instead provided via AXI-4 to the accelerator from the processing system using those buffers
