### ISSUE TITLE
Training of WnAn

### ISSUE THREAD

**Issue by mohdumar644** [Xilinx/BNN-PYNQ#60]
I noticed an update to the BNN-PYNQ library adding support for WnAn.

Can you please give a pointer as to what quantization scheme are you using, and what framework?

From the finnthesizer, it does not look like you are using DoReFa-Net like you used in QNN-MO-PYNQ.

**Comment by nickfraser** [comment]
We're planning to release the training scripts by the end of this week - I hope this will answer all of your questions.

**Comment by mohdumar644** [comment]
Can you link a research paper, if you have implemented that?

**Comment by mohdumar644** [comment]
Thanks, but your paper did not define the quantization function exactly, and I could not decipher the function from the finnthesizer. Are there more any more hints?

**Comment by mohdumar644** [comment]
What does the s0.5 and s0.25 imply in the given ``.npz`` names?

**Comment by nickfraser** [comment]
There is actually no (relevant) meaning to those. It's related to the topological description of CNV & LFC - these values are simply hardcoded into the cnv/lfc.py files respectively.

Apologies again for the delay, we plan to upload the training scripts for these this week.

**Comment by mohdumar644** [comment]
Thanks, I was able to train a 2 bit and a 4 bit network using the -.5,.5 and equidistant thresholds respectively.
