### ISSUE TITLE
CNV on No. of classes greater than 64

### ISSUE THREAD

**Issue by ussamazahid96** [Xilinx/BNN-PYNQ#63]
I am trying to extend the no. classes to greater than 64 e.g. trying to use CNV with CIFAR-100. 

Is there any specific reason why max no. of classes is fixed to 64? Is this related 64-bit bus alignment?

Thanks!

**Comment by giuliogamba** [comment]
There is no specific reasons about why we set the value to 64, you can increase the number of classes if you want. You can change in the hardware the value `L8_MH`  in the [config](https://github.com/Xilinx/BNN-PYNQ/blob/master/bnn/src/network/cnvW1A1/hw/config.h) file to the needed number of classes.
