### ISSUE TITLE
Doubt about pragma in HLS code

### ISSUE THREAD

**Issue by saraballeri** [Xilinx/BNN-PYNQ#64]
Hi, 
I have a doubt about the following piece of code in `top.cpp`
```
// signals to be mapped to the AXI master port (hostmem)
#pragma HLS INTERFACE m_axi offset=slave port=in bundle=hostmem depth=512
#pragma HLS INTERFACE s_axilite port=in bundle=control
#pragma HLS INTERFACE m_axi offset=slave port=out bundle=hostmem depth=16
#pragma HLS INTERFACE s_axilite port=out bundle=control
```

The two HLS INTERFACE m_axi have an offset=slave, then Vivado generates for each of them an offset port mapping them as Axi4-Lite slave interfaces.
Indeed, I have seen that the driver automatically creates the two data signal related to these slave interfaces.
Then, what is the functionality of the other two HLS INTERFACE s_axilite? 
If I delete these two HLS INTERFACE s_axilite the driver doesn't change.

Thanks,
Sara

**Comment by giuliogamba** [comment]
It might be redundant, but it assures that the axi-lite register used for the m_axi address is bundled in the same axi_lite interface (the bundle control used for the other axi_lite registers).
