### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by YNZH** [Xilinx/BNN-PYNQ#65]
![image](https://user-images.githubusercontent.com/24869527/49138406-09990780-f32a-11e8-970f-f3ed6d036414.png)

**Comment by giuliogamba** [comment]
This problem is not related to this repository (and I can't reproduce it on my system). 
If the issue persist, consider opening an issue under [PYNQ](https://github.com/Xilinx/PYNQ/issues/)
