### ISSUE TITLE
Make a CNV with 3 bit of Activation function

### ISSUE THREAD

**Issue by FrancoCapraro** [Xilinx/BNN-PYNQ#69]
Hi, im trying to change from 2 to 3 of Activation function.I saw a really great change from CNVW1A1 to CNVW1A2, so i want to try improve it but i want know if i am doing right.

What i need do:
Network:

1) Change the **config.h** file > the  #define's of **Lx_API to 3**, but in the last layer it will be L8_API = 1 ?

2) Change the **FoldedMVInit** function in foldedmv-offload.cpp ?

Training(for Cifar10 as example):

3) Change the **ActivationPrecisions_integer** and **InputPrecisions_integer** ?

Bitstream

4) I need to regenarate the bitstream with my new cnv Network

Let me know if im forgetting something.
About the Utilization, i will use it in Ultra96. i saw the Report Utilization and i think can fit. (Im new so, maybe its a mistake)

**Comment by giuliogamba** [comment]
First of all you need to train your neural network with the proper precision, as explained [here](https://github.com/Xilinx/BNN-PYNQ/tree/master/bnn/src/training). Following that, you should change the bitwidths in the weight export script (as example for [W1A2 ](https://github.com/Xilinx/BNN-PYNQ/blob/master/bnn/src/training/cifar10-gen-weights-W1A2.py)and [W2A2](https://github.com/Xilinx/BNN-PYNQ/blob/master/bnn/src/training/cifar10-gen-weights-W2A2.py). 
The config file will be automatically generated.

**Comment by hsinyuting** [comment]
Hi, thanks for the update of docker's environment, I had trained W1A3.
In terms of the weight export script, I modify W1A2 into
ActivationPrecisions_integer =    [3 , 3 , 3 , 3 , 3 , 3 , 3, 3, 1]
InputPrecisions_integer =         [1 , 3 , 3 , 3 , 3 , 3 , 3, 3, 3], 
,then copy the new config file and replicate top.cpp in W1A2, modify into ap_int<3> bits,
and copy the param to the right directory.

When I started running hls, in the csim, it shows such warnings and predicts the wrong class.
--
WARNING: Hls::stream 'hls::stream<ap_uint<96> >.1' contains leftover data, which may result in RTL simulation hanging.
WARNING: Hls::stream 'DoCompute.inter2' is read while empty, which may result in RTL simulation hanging.
...
WARNING: Hls::stream 'DoCompute.inter5' contains leftover data, which may result in RTL simulation hanging.
WARNING: Hls::stream 'DoCompute.inter4' contains leftover data, which may result in RTL simulation hanging.
WARNING: Hls::stream 'DoCompute.inter1' contains leftover data, which may result in RTL simulation hanging.
...
--
It seems like some data are not present before reading and the leftover data. 
Can you hint what I might miss?

**Comment by giuliogamba** [comment]
There are a couple of mistakes:

1. The precisions with 3 bits is actually ap_fixed<3,1>, so with 1 bits for integer part and 2 bits for fractional part. For example: 
`    WeightsPrecisions_integer =       [2 , 2 , 2 , 2 , 2 , 2 , 2, 2, 2]`
`    WeightsPrecisions_fractional =    [1 , 1 , 1 , 1 , 1 , 1 , 1, 1, 1]`
2. You should also adapt the weight type definition in top.cpp to the new precision. For example:
`static FixedPointWeights<L0_SIMD, ap_fixed<L0_WPI + L0_WPF, L0_WPI, AP_TRN, AP_WRAP>, L0_PE, L0_WMEM>   weights0;`
3. You should adapt the precision for the layers. For example:
`    ConvLayer_Batch<L1_K, L1_IFM_CH, L1_IFM_DIM, L1_OFM_CH, L1_OFM_DIM, L1_SIMD, L1_PE, Slice<ap_fixed<3,1, AP_TRN, AP_WRAP>>, Slice<ap_int<3>>, Identity>(inter1, inter2, weights1, threshs1, numReps, ap_resource_lut());`

Hope this helps

**Comment by gsr-ee** [comment]
You missed the shared libraries. How can I generate the shared libraries for a different precision???
