### ISSUE TITLE
Problem about hardware design rebuilt, 'Vivado not found'

### ISSUE THREAD

**Issue by jihye0005** [Xilinx/BNN-PYNQ#72]
Hi!
I installed Vivado2018.2. 
I'm trying to rebuild the hardware desing, but have a problem.

![image](https://user-images.githubusercontent.com/25446103/50758411-7dbdb800-12a5-11e9-8095-1a7984d655bb.png)

Help me please~.
Thanks a lot!

**Comment by giuliogamba** [comment]
Possibly you installed Vivado but haven't sourced it. 
Please refer to pag.39 of this [document](https://www.xilinx.com/content/dam/xilinx/support/documentation/sw_manuals/xilinx2018_3/ug973-vivado-release-notes-install-license.pdf)

**Comment by maik123456789** [comment]
HI! I have the same problem but I cannot solved, what am I doing wrong? 
![image](https://user-images.githubusercontent.com/54273123/91090519-83703900-e655-11ea-813e-e5736d0d74df.png)
