### ISSUE TITLE
How can I combine between the BNN-CNV- Overlay and PYNQ-Base-Overlay ?

### ISSUE THREAD

**Issue by houssem123456** [Xilinx/BNN-PYNQ#77]
Hi all,
I'm a beginner with vivado IP integrator.

Now I'm working in a project that combine between the base overlay of PYNQ-Z1 and BNN-PYNQ.

I'm trying to launch Cifar10 in Hardware after capturing Video through HDMI-in.

In fact, I will apply on each frame of this video the "CnvClassifier"(CNV overlay ) to detect objects.
However  I found that the CNV overlay does not have neither HDMI in nor HDMI out and only the base overlay of the pynq does have. So every time I need to use HDMI, the base overlay has to be downloaded, and every time i need to use CNV the CNV overlay has to be downloaded too and this of course is not passable.

My question : How to integrate the CNV ip core within the base overlay (In VIVADO IP INTEGRATOR ) so that I can generate my own overlay with both CNV and HDMI ?
Any help please!!

 Best Regards.

**Comment by giuliogamba** [comment]
You have to act at Vivado IP integrator level, in this repository you can generate only the CNV IP by launching the `make-hw.sh` script with the flag `-h`. Then you can generate the IP block design from the [PYNQ ](https://github.com/xilinx/pynq) repository for the base overlay and manually add the BNN IP.
