### ISSUE TITLE
Doubt about the use of tiny-cnn framework

### ISSUE THREAD

**Issue by saraballeri** [Xilinx/BNN-PYNQ#79]
Hi, 
reading the source code of BNN-PYNQ framework (in particular the code of cnvW1A1 network), I noted many function calls at the tiny-cnn framework.
I don't understand how tiny-cnn can be useful for your framework since the entire network is implemented in hardware.
For example with the function [makeNetwork](https://github.com/Xilinx/BNN-PYNQ/blob/2b502ddb57aa4010fb34e4e36c7e1fb95902684c/bnn/src/network/cnvW1A1/sw/main_python.cpp#L56) a network with only two types of layers (chaninterleave_layer and offloaded_layer) is created, but the network is composed of many other layers. Moreover, what the define OFFLOAD refers to?
Another point in which tiny-cnn is used is [that](https://github.com/Xilinx/BNN-PYNQ/blob/2b502ddb57aa4010fb34e4e36c7e1fb95902684c/bnn/src/library/host/foldedmv-offload.h#L496). Here I think that tiny-cnn is used to load the test images. Right? But it is necessary or I can load directly my binary images?

Thanks,

Sara

**Comment by giuliogamba** [comment]
We do use some convenience functions from tiny-cnn, like the load of input images. 
Additionally some layers have been added, like the OFFLOAD, is order to manage the hardware offload of the network.

**Comment by saraballeri** [comment]
Hi,
thank for your response.
But in particular what is the aim of these two functions in the loop?
```
for(unsigned int i = 0; i < count; i++) {
    tiny_cnn::vec_t interleaved = interleaver.forward_propagation(imgs[i], 0);
    quantiseAndPack<inWidth, 1>(interleaved, &packedImages[i * psi], psi);
}
```
Is there a documentation about tiny-cnn other than github repo?

Thanks,

Sara

**Comment by aquibjamal** [comment]
Hi,

I am trying to use the tiny_cnn library on ESP32 board.
There is a reboot when the code reaches the declaration of **interleaver** in the function **testPrebuiltCIFAR10_from_image()**.
I would be grateful for any support in understanding what is the use of **interleaver** and if there is any workaround to directly use the **imgs** vector if I don't want to use interleaved inputs for inference.

With regards
Aquib
