### ISSUE TITLE
Making a network with a new dataset

### ISSUE THREAD

**Issue by mgepner** [Xilinx/BNN-PYNQ#8]
In BNN-PYNQ/bnn/src/training/lfc.py it says that changing the file will likely result in not fitting on the PYNQ overlay. Is it possible to change the units, layers, and shape without having to worry? I am currently running it with changes but am unsure if it will not work later on.

**Comment by giuliogamba** [comment]
There are 2 available overlays, each one implementing a neural network (LFC and CNV). If you want to use one of the available overlays, you need to train the network using one of the available topology. 
If you want to change the network topology during training, you will need to adjust the network topology in the HLS description accordingly and regenerate a new overlay.
