### ISSUE TITLE
The kernel appears to have died. It will restart automatically.

### ISSUE THREAD

**Issue by Changyiyu** [Xilinx/BNN-PYNQ#80]
Hello:

I try the lab of "CNV-BNN_Road-Signs.ipynb", but I encountered the problem of kernel death when I went to step four "Launching BNN in hardware". How can I solve this problem?

**Comment by giuliogamba** [comment]
Does this happen with all notebooks or just with that one? Which board are you using?

**Comment by Changyiyu** [comment]
I just try this notebook. The board I use PYNQ-Z2.

**Comment by giuliogamba** [comment]
Can you please try if the problem exists with the other notebooks?

**Comment by giuliogamba** [comment]
@Changyiyu can you please check if the issue persists after the latest update?

**Comment by Changyiyu** [comment]
Hello,
Sorry, It's my fault. I've tried other notebooks, but the problem is that my working path of images is wrong. Thanks for your help.
