### ISSUE TITLE
Training CNV networks

### ISSUE THREAD

**Issue by Sayf-Khan** [Xilinx/BNN-PYNQ#84]
Hi,

I have tried to train the cifar10 netowork without any modification to the .py file.

I have followed the instructions to install the prerequisites, however opun ececution I have the following error. 

sayf@sayf-MS-7B61:~/BNN-PYNQ/bnn/src/training$ python cifar10.py -wb 1 -ab 1
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release.  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: GeForce GTX 1080 Ti (CNMeM is disabled, cuDNN 5110)
activation_bits = 1
weight_bits = 1
batch_size = 50
alpha = 0.1
epsilon = 0.0001
W_LR_scale = Glorot
num_epochs = 500
LR_start = 0.001
LR_fin = 3e-07
LR_decay = 0.983907435305
save_path = cifar10-1w-1a.npz
train_set_size = 45000
shuffle_parts = 1
Loading CIFAR-10 dataset...
Traceback (most recent call last):
  File "cifar10.py", line 119, in <module>
    train_set = CIFAR10(which_set="train",start=0,stop = train_set_size)
  File "/home/sayf/pylearn2/pylearn2/datasets/cifar10.py", line 71, in __init__
    string_utils.preprocess('${PYLEARN2_DATA_PATH}'),
  File "/home/sayf/pylearn2/pylearn2/utils/string_utils.py", line 56, in preprocess
    reraise_as(NoDataPathError())
  File "/home/sayf/pylearn2/pylearn2/utils/exc.py", line 90, in reraise_as
    six.reraise(type(new_exc), new_exc, orig_exc_traceback)
  File "/home/sayf/pylearn2/pylearn2/utils/string_utils.py", line 53, in preprocess
    else os.environ[varname])
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
pylearn2.utils.exc.NoDataPathError: You need to define your PYLEARN2_DATA_PATH environment variable. If you are
using a computer at LISA, this should be set to /data/lisa/data.

Platform-specific instructions for setting environment variables:

Linux
=====
On most linux setups, you can define your environment variable by adding this
line to your ~/.bashrc file:

export PYLEARN2_VIEWER_COMMAND="eog --new-instance"

*** YOU MUST INCLUDE THE WORD "export". DO NOT JUST ASSIGN TO THE ENVIRONMENT VARIABLE ***
If you do not include the word "export", the environment variable will be set
in your bash shell, but will not be visible to processes that you launch from
it, like the python interpreter.

Don't forget that changes from your .bashrc file won't apply until you run

source ~/.bashrc

or open a new terminal window. If you're seeing this from an ipython notebook
you'll need to restart the ipython notebook, or maybe modify os.environ from
an ipython cell.

Mac OS X
========

Environment variables on Mac OS X work the same as in Linux, except you should
modify and run the "source" command on ~/.profile rather than ~/.bashrc.

Original exception:
	KeyError: PYLEARN2_DATA_PATH

I have modified the bashrc and have sourced it yet it causes the same problem.

Any help will be much appreciated.

Kind regards,
Sayf Khan

**Comment by nickfraser** [comment]
As the error suggests, you have not set the PYLEARN2_DATA_PATH variable as specified [here](https://github.com/Xilinx/BNN-PYNQ/tree/master/bnn/src/training#download-datasets). If you would like this environment variable to persist, please add the line `export PYLEARN2_DATA_PATH=~/.pylearn2` to your `.bashrc` file or similar.
