### ISSUE TITLE
Hints for latency reduction

### ISSUE THREAD

**Issue by saraballeri** [Xilinx/BNN-PYNQ#86]
Hi,
I'm doing some experiments about your BNN implementation.
Question 1:
In your opinion, could be possible to use a "non-square dimension" input image with the appropriate code changes(I think stream sizes, PE, SIMD, etc.. values)? For example, an input image of 32x16 in cnvW1A1 network.

Question 2:
Running the script cifar10-gen-weights-W1A1.py I note that if I duplicate the "PE counts" of a layer (eg. the first convolutional layer) the latency of this layer is reduced by 50%.
Since I need to leverage this latency reduction, what is it necessary to do so that the network works fine?Weights and thresholds parameters must be regenerated?Or whatever?

Thanks a lot for your help!

Sara

**Comment by giuliogamba** [comment]
Hi, 
1. It's possible to have non-square feature maps, but that required changes in the HLS library. 
2. Each layer has a latency which is estimated when generating the `config.h` file. The overall latency of the network is related to the sum of the latencies of each layer, while the throughput depends on the maximum latencies among all layers. If you change SIMD and PE, you will need to regenerate the HW, load the new generated parameters and re-make the .so.

Hope this helps.
