### ISSUE TITLE
Retrain the BNN

### ISSUE THREAD

**Issue by vesaalexandru95** [Xilinx/BNN-PYNQ#89]
Hello.
I have one question. If i want to retrain the BNN , I saw that the format of data must be in one hot ecoding. What program should i use for labelling? Thanks. Alex

**Comment by nickfraser** [comment]
It's not necessary to use a specific program to label the data. See [here](https://github.com/Xilinx/BNN-PYNQ/blob/master/bnn/src/training/mnist.py#L143) which converts the labels from integers (the numbers 0-9), to [One-hot encoding](https://en.wikipedia.org/wiki/One-hot).
