### ISSUE TITLE
FINN features not supported in BNN-PYNQ

### ISSUE THREAD

**Issue by saraballeri** [Xilinx/BNN-PYNQ#91]
Hi,
reading some papers about FINN, sometimes the repo BNN-PYNQ is referred as "lightweight version of FINN".
But, what are the features of FINN that are not supported by BNN-PYNQ?
Best regards.
Thanks,

Sara

**Comment by giuliogamba** [comment]
This repo does not implement the complete FINN toolflow (which consist of automatic generation of the hardware accelerator starting from a trained neural network in Caffe). 
You can find more information about the different repos and their features in our webpage: http://www.pynq.io/ml
