### ISSUE TITLE
Generate  Binary Weights Files

### ISSUE THREAD

**Issue by vesaalexandru95** [Xilinx/BNN-PYNQ#93]
Hello,
I have one question. After I retrained the bnn on my own dataset, how do i generate the Binary weights files? Thanks a lot, Alex

**Comment by giuliogamba** [comment]
Have you read the paragraph with title _Generating Binary Weights Files_ in the [readme ](https://github.com/Xilinx/BNN-PYNQ/blob/master/bnn/src/training/README.md)?
