### ISSUE TITLE
Increase the CNV classification speed

### ISSUE THREAD

**Issue by HungSoma** [Xilinx/BNN-PYNQ#94]
Hi everyone,
I'm using BNN-PYNQ on Pynq v2.4 for real time object detection ( frame by frame from video ), but time for BNN is not fast enough to get high performance. I tried to use 
`       start_timet = time.time() 
        result = classifier.classify_cifars_details(fp.name)  
        end_timet = time.time()`
to check  time consume (using terminal) then
result_time = end_timet - start_timet = 0.022214889526367188 per image
Maybe data transmission time between PS and PL on Pynq is high  . I would like to increase speed of  BNN classification and I saw an old issue :
![image](https://user-images.githubusercontent.com/29880226/57234883-dd598380-704b-11e9-81dd-2715445a1220.png)
I dont know how to change values of SIMD and PE counts 
![image](https://user-images.githubusercontent.com/29880226/57235147-71c3e600-704c-11e9-9152-f3932340fee8.png)
Can you help me with this?
Regards,
Hung

**Comment by giuliogamba** [comment]
Hi, 

according to your measured time, you should be able to run at 45 frames per second. Do you have a video source providing data at higher frame rate? Which board are you using?
