### ISSUE TITLE
Vivado-hls resource utilization is much better

### ISSUE THREAD

**Issue by wpyueyue** [Xilinx/BNN-PYNQ#97]
The board I use is pynqZ2,But the viv and hrs report has a lot more FF and LUT resources.The vivado project also broke fatal errors. But it can generate bit files.

**Comment by giuliogamba** [comment]
Hi, the Vivado HLS Estimate usage sometimes can be conservative.
Vivado will perform further optimizations and you should see a smaller hardware usage after place and route. Can you please give more details about the fatal errors in Vivado?

**Comment by giuliogamba** [comment]
Closed due to inactivity
